# file: roles/dotfiles/tasks/dan.yml

---
# files ------------------------------------------------------------------- {{{
- name: dan | mkdir -p dotfiles.dan.directories
  file: name={{ item }} state=directory
  with_items: dotfiles.dan.directories
# /files ------------------------------------------------------------------ }}}

# repos ------------------------------------------------------------------- {{{
- name: dan | hg clone dotfiles.dan.hg.repos
  hg: repo={{ item.repo }} dest={{ item.dest }}
  with_items: dotfiles.dan.hg.repos

- name: dan | git clone dotfiles.dan.git.repos
  git: repo={{ item.repo }} dest={{ item.dest }}
  with_items: dotfiles.dan.git.repos
# /repos ------------------------------------------------------------------ }}}

# rbenv ------------------------------------------------------------------- {{{
# - name: dan | rbenv install dotfiles.dan.ruby.version
#   shell: "{{ dotfiles.dan.rbenv.commands.rbenv_install_ruby }}"
# 
# - name: dan | rbenv global dotfiles.dan.ruby.version
#   shell: "{{ dotfiles.dan.rbenv.commands.rbenv_global_ruby }}"
# 
# - name: dan | gem install bundler
#   shell: "{{ dotfiles.dan.rbenv.commands.gem_install_bundler }}"
# /rbenv ------------------------------------------------------------------ }}}

# dotfiles ---------------------------------------------------------------- {{{
# - name: dan | rake install dotfiles
#   shell: "{{ dotfiles.dan.dotfiles.commands.install }}"

- name: dan | ln -s ~/.tmux.system.conf ~/.tmux.conf
  file: "src={{ dan.home }}/.tmux.{{ system }}.conf dest={{ dan.home }}/.tmux.conf state=link"
# /dotfiles --------------------------------------------------------------- }}}
